server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.10.100:3306/chatroom?useUnicode=true&characterEncoding=utf8
    username: root
    password: 2333
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# fastdfs client 配置
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.10.100:22122
